{
 "title": "ISUCON",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top10 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "topk(10, process_cpu_usage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "topk(10, process_memory_usage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_cpu_user", "legendFormat": "User" },
    { "expr": "node_cpu_system", "legendFormat": "System" },
    { "expr": "node_cpu_nice", "legendFormat": "Nice" },
    { "expr": "node_cpu_idle", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "Access Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"nginx\", type=\"access\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(uri_normalized, method_normalized) (count by(uri_normalized, method_normalized) (count_over_time({app=\"nginx\", type=\"access\"} | json request_time=\"request_time\" [$__auto])))"
    },
    {
     "expr": "avg by(uri_normalized, method_normalized) (avg by(uri_normalized, method_normalized) (avg_over_time({app=\"nginx\", type=\"access\"} | json request_time=\"request_time\" | unwrap request_time [$__auto])))"
    },
    {
     "expr": "max by(uri_normalized, method_normalized) (max by(uri_normalized, method_normalized) (max_over_time({app=\"nginx\", type=\"access\"} | json request_time=\"request_time\" | unwrap request_time [$__auto])))"
    },
    {
     "expr": "min by(uri_normalized, method_normalized) (min by(uri_normalized, method_normalized) (min_over_time({app=\"nginx\", type=\"access\"} | json request_time=\"request_time\" | __error__=`` | unwrap request_time [$__auto])))"
    },
    {
     "expr": "sum by(uri_normalized, method_normalized) (count by(uri_normalized, method_normalized) (count_over_time({app=\"nginx\", type=\"access\", status_normalized=\"2XX\"} | json request_time=\"request_time\" [$__auto]))) "
    },
    {
     "expr": "sum by(uri_normalized, method_normalized) (count by(uri_normalized, method_normalized) (count_over_time({app=\"nginx\", type=\"access\", status_normalized=\"5XX\"} | json request_time=\"request_time\" [$__auto]))) "
    },
    {
     "expr": "sum by(uri_normalized, method_normalized) (count by(uri_normalized, method_normalized) (count_over_time({app=\"nginx\", type=\"access\", status_normalized=\"4XX\"} | json request_time=\"request_time\" [$__auto]))) "
    }
   ]
  },
  {
   "title": "Trace",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 34 },
   "targets": [
    {
     "filters": [
      { "id": "1e147db2", "operator": "=", "scope": "resource" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "unknown_service:isupipe" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "HTTP GET route not found" ],
       "valueType": "string"
      },
      { "id": "duration-type", "value": "trace" }
     ],
     "limit": 100,
     "query": "{resource.service.name=\"unknown_service:isupipe\" && name=\"/api/livestream/reservation\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  }
 ]
}